# coding: utf-8

"""
    Shoko API 3

    Shoko Server API.  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from lib.shoko.v3 import schemas  # noqa: F401


class DataModelsRelationType(
    schemas.EnumBase,
    schemas.Int32Schema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        format = 'int32'
        enum_value_to_name = {
            0: "POSITIVE_0",
            1: "POSITIVE_1",
            2: "POSITIVE_2",
            3: "POSITIVE_3",
            4: "POSITIVE_4",
            20: "POSITIVE_20",
            21: "POSITIVE_21",
            22: "POSITIVE_22",
            40: "POSITIVE_40",
            41: "POSITIVE_41",
            42: "POSITIVE_42",
        }
    
    @schemas.classproperty
    def POSITIVE_0(cls):
        return cls(0)
    
    @schemas.classproperty
    def POSITIVE_1(cls):
        return cls(1)
    
    @schemas.classproperty
    def POSITIVE_2(cls):
        return cls(2)
    
    @schemas.classproperty
    def POSITIVE_3(cls):
        return cls(3)
    
    @schemas.classproperty
    def POSITIVE_4(cls):
        return cls(4)
    
    @schemas.classproperty
    def POSITIVE_20(cls):
        return cls(20)
    
    @schemas.classproperty
    def POSITIVE_21(cls):
        return cls(21)
    
    @schemas.classproperty
    def POSITIVE_22(cls):
        return cls(22)
    
    @schemas.classproperty
    def POSITIVE_40(cls):
        return cls(40)
    
    @schemas.classproperty
    def POSITIVE_41(cls):
        return cls(41)
    
    @schemas.classproperty
    def POSITIVE_42(cls):
        return cls(42)
