# coding: utf-8

"""
    Shoko API 3

    Shoko Server API.  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from lib.shoko.v3 import schemas  # noqa: F401


class DataModelsTitleLanguage(
    schemas.EnumBase,
    schemas.Int32Schema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        format = 'int32'
        enum_value_to_name = {
            0: "POSITIVE_0",
            1: "POSITIVE_1",
            2: "POSITIVE_2",
            3: "POSITIVE_3",
            4: "POSITIVE_4",
            5: "POSITIVE_5",
            6: "POSITIVE_6",
            7: "POSITIVE_7",
            8: "POSITIVE_8",
            9: "POSITIVE_9",
            10: "POSITIVE_10",
            11: "POSITIVE_11",
            12: "POSITIVE_12",
            13: "POSITIVE_13",
            14: "POSITIVE_14",
            15: "POSITIVE_15",
            16: "POSITIVE_16",
            17: "POSITIVE_17",
            18: "POSITIVE_18",
            19: "POSITIVE_19",
            20: "POSITIVE_20",
            21: "POSITIVE_21",
            22: "POSITIVE_22",
            23: "POSITIVE_23",
            24: "POSITIVE_24",
            25: "POSITIVE_25",
            26: "POSITIVE_26",
            27: "POSITIVE_27",
            28: "POSITIVE_28",
            29: "POSITIVE_29",
            30: "POSITIVE_30",
            31: "POSITIVE_31",
            32: "POSITIVE_32",
            33: "POSITIVE_33",
            34: "POSITIVE_34",
            35: "POSITIVE_35",
            36: "POSITIVE_36",
            37: "POSITIVE_37",
            38: "POSITIVE_38",
            39: "POSITIVE_39",
            40: "POSITIVE_40",
            41: "POSITIVE_41",
            42: "POSITIVE_42",
            43: "POSITIVE_43",
            44: "POSITIVE_44",
            45: "POSITIVE_45",
            46: "POSITIVE_46",
            47: "POSITIVE_47",
            48: "POSITIVE_48",
            49: "POSITIVE_49",
            50: "POSITIVE_50",
            51: "POSITIVE_51",
            52: "POSITIVE_52",
            53: "POSITIVE_53",
            54: "POSITIVE_54",
            55: "POSITIVE_55",
            56: "POSITIVE_56",
            57: "POSITIVE_57",
            58: "POSITIVE_58",
            59: "POSITIVE_59",
            60: "POSITIVE_60",
            61: "POSITIVE_61",
            62: "POSITIVE_62",
            63: "POSITIVE_63",
            64: "POSITIVE_64",
            65: "POSITIVE_65",
            66: "POSITIVE_66",
            67: "POSITIVE_67",
            68: "POSITIVE_68",
            69: "POSITIVE_69",
            70: "POSITIVE_70",
            71: "POSITIVE_71",
            72: "POSITIVE_72",
            73: "POSITIVE_73",
            74: "POSITIVE_74",
            75: "POSITIVE_75",
            76: "POSITIVE_76",
            77: "POSITIVE_77",
            78: "POSITIVE_78",
            79: "POSITIVE_79",
            80: "POSITIVE_80",
            81: "POSITIVE_81",
            82: "POSITIVE_82",
            83: "POSITIVE_83",
            84: "POSITIVE_84",
            85: "POSITIVE_85",
            86: "POSITIVE_86",
            87: "POSITIVE_87",
            88: "POSITIVE_88",
            89: "POSITIVE_89",
            90: "POSITIVE_90",
            91: "POSITIVE_91",
            92: "POSITIVE_92",
            93: "POSITIVE_93",
            94: "POSITIVE_94",
            95: "POSITIVE_95",
            96: "POSITIVE_96",
            97: "POSITIVE_97",
            98: "POSITIVE_98",
            99: "POSITIVE_99",
            100: "POSITIVE_100",
            101: "POSITIVE_101",
            102: "POSITIVE_102",
            103: "POSITIVE_103",
            104: "POSITIVE_104",
            105: "POSITIVE_105",
            106: "POSITIVE_106",
            107: "POSITIVE_107",
            108: "POSITIVE_108",
            109: "POSITIVE_109",
        }
    
    @schemas.classproperty
    def POSITIVE_0(cls):
        return cls(0)
    
    @schemas.classproperty
    def POSITIVE_1(cls):
        return cls(1)
    
    @schemas.classproperty
    def POSITIVE_2(cls):
        return cls(2)
    
    @schemas.classproperty
    def POSITIVE_3(cls):
        return cls(3)
    
    @schemas.classproperty
    def POSITIVE_4(cls):
        return cls(4)
    
    @schemas.classproperty
    def POSITIVE_5(cls):
        return cls(5)
    
    @schemas.classproperty
    def POSITIVE_6(cls):
        return cls(6)
    
    @schemas.classproperty
    def POSITIVE_7(cls):
        return cls(7)
    
    @schemas.classproperty
    def POSITIVE_8(cls):
        return cls(8)
    
    @schemas.classproperty
    def POSITIVE_9(cls):
        return cls(9)
    
    @schemas.classproperty
    def POSITIVE_10(cls):
        return cls(10)
    
    @schemas.classproperty
    def POSITIVE_11(cls):
        return cls(11)
    
    @schemas.classproperty
    def POSITIVE_12(cls):
        return cls(12)
    
    @schemas.classproperty
    def POSITIVE_13(cls):
        return cls(13)
    
    @schemas.classproperty
    def POSITIVE_14(cls):
        return cls(14)
    
    @schemas.classproperty
    def POSITIVE_15(cls):
        return cls(15)
    
    @schemas.classproperty
    def POSITIVE_16(cls):
        return cls(16)
    
    @schemas.classproperty
    def POSITIVE_17(cls):
        return cls(17)
    
    @schemas.classproperty
    def POSITIVE_18(cls):
        return cls(18)
    
    @schemas.classproperty
    def POSITIVE_19(cls):
        return cls(19)
    
    @schemas.classproperty
    def POSITIVE_20(cls):
        return cls(20)
    
    @schemas.classproperty
    def POSITIVE_21(cls):
        return cls(21)
    
    @schemas.classproperty
    def POSITIVE_22(cls):
        return cls(22)
    
    @schemas.classproperty
    def POSITIVE_23(cls):
        return cls(23)
    
    @schemas.classproperty
    def POSITIVE_24(cls):
        return cls(24)
    
    @schemas.classproperty
    def POSITIVE_25(cls):
        return cls(25)
    
    @schemas.classproperty
    def POSITIVE_26(cls):
        return cls(26)
    
    @schemas.classproperty
    def POSITIVE_27(cls):
        return cls(27)
    
    @schemas.classproperty
    def POSITIVE_28(cls):
        return cls(28)
    
    @schemas.classproperty
    def POSITIVE_29(cls):
        return cls(29)
    
    @schemas.classproperty
    def POSITIVE_30(cls):
        return cls(30)
    
    @schemas.classproperty
    def POSITIVE_31(cls):
        return cls(31)
    
    @schemas.classproperty
    def POSITIVE_32(cls):
        return cls(32)
    
    @schemas.classproperty
    def POSITIVE_33(cls):
        return cls(33)
    
    @schemas.classproperty
    def POSITIVE_34(cls):
        return cls(34)
    
    @schemas.classproperty
    def POSITIVE_35(cls):
        return cls(35)
    
    @schemas.classproperty
    def POSITIVE_36(cls):
        return cls(36)
    
    @schemas.classproperty
    def POSITIVE_37(cls):
        return cls(37)
    
    @schemas.classproperty
    def POSITIVE_38(cls):
        return cls(38)
    
    @schemas.classproperty
    def POSITIVE_39(cls):
        return cls(39)
    
    @schemas.classproperty
    def POSITIVE_40(cls):
        return cls(40)
    
    @schemas.classproperty
    def POSITIVE_41(cls):
        return cls(41)
    
    @schemas.classproperty
    def POSITIVE_42(cls):
        return cls(42)
    
    @schemas.classproperty
    def POSITIVE_43(cls):
        return cls(43)
    
    @schemas.classproperty
    def POSITIVE_44(cls):
        return cls(44)
    
    @schemas.classproperty
    def POSITIVE_45(cls):
        return cls(45)
    
    @schemas.classproperty
    def POSITIVE_46(cls):
        return cls(46)
    
    @schemas.classproperty
    def POSITIVE_47(cls):
        return cls(47)
    
    @schemas.classproperty
    def POSITIVE_48(cls):
        return cls(48)
    
    @schemas.classproperty
    def POSITIVE_49(cls):
        return cls(49)
    
    @schemas.classproperty
    def POSITIVE_50(cls):
        return cls(50)
    
    @schemas.classproperty
    def POSITIVE_51(cls):
        return cls(51)
    
    @schemas.classproperty
    def POSITIVE_52(cls):
        return cls(52)
    
    @schemas.classproperty
    def POSITIVE_53(cls):
        return cls(53)
    
    @schemas.classproperty
    def POSITIVE_54(cls):
        return cls(54)
    
    @schemas.classproperty
    def POSITIVE_55(cls):
        return cls(55)
    
    @schemas.classproperty
    def POSITIVE_56(cls):
        return cls(56)
    
    @schemas.classproperty
    def POSITIVE_57(cls):
        return cls(57)
    
    @schemas.classproperty
    def POSITIVE_58(cls):
        return cls(58)
    
    @schemas.classproperty
    def POSITIVE_59(cls):
        return cls(59)
    
    @schemas.classproperty
    def POSITIVE_60(cls):
        return cls(60)
    
    @schemas.classproperty
    def POSITIVE_61(cls):
        return cls(61)
    
    @schemas.classproperty
    def POSITIVE_62(cls):
        return cls(62)
    
    @schemas.classproperty
    def POSITIVE_63(cls):
        return cls(63)
    
    @schemas.classproperty
    def POSITIVE_64(cls):
        return cls(64)
    
    @schemas.classproperty
    def POSITIVE_65(cls):
        return cls(65)
    
    @schemas.classproperty
    def POSITIVE_66(cls):
        return cls(66)
    
    @schemas.classproperty
    def POSITIVE_67(cls):
        return cls(67)
    
    @schemas.classproperty
    def POSITIVE_68(cls):
        return cls(68)
    
    @schemas.classproperty
    def POSITIVE_69(cls):
        return cls(69)
    
    @schemas.classproperty
    def POSITIVE_70(cls):
        return cls(70)
    
    @schemas.classproperty
    def POSITIVE_71(cls):
        return cls(71)
    
    @schemas.classproperty
    def POSITIVE_72(cls):
        return cls(72)
    
    @schemas.classproperty
    def POSITIVE_73(cls):
        return cls(73)
    
    @schemas.classproperty
    def POSITIVE_74(cls):
        return cls(74)
    
    @schemas.classproperty
    def POSITIVE_75(cls):
        return cls(75)
    
    @schemas.classproperty
    def POSITIVE_76(cls):
        return cls(76)
    
    @schemas.classproperty
    def POSITIVE_77(cls):
        return cls(77)
    
    @schemas.classproperty
    def POSITIVE_78(cls):
        return cls(78)
    
    @schemas.classproperty
    def POSITIVE_79(cls):
        return cls(79)
    
    @schemas.classproperty
    def POSITIVE_80(cls):
        return cls(80)
    
    @schemas.classproperty
    def POSITIVE_81(cls):
        return cls(81)
    
    @schemas.classproperty
    def POSITIVE_82(cls):
        return cls(82)
    
    @schemas.classproperty
    def POSITIVE_83(cls):
        return cls(83)
    
    @schemas.classproperty
    def POSITIVE_84(cls):
        return cls(84)
    
    @schemas.classproperty
    def POSITIVE_85(cls):
        return cls(85)
    
    @schemas.classproperty
    def POSITIVE_86(cls):
        return cls(86)
    
    @schemas.classproperty
    def POSITIVE_87(cls):
        return cls(87)
    
    @schemas.classproperty
    def POSITIVE_88(cls):
        return cls(88)
    
    @schemas.classproperty
    def POSITIVE_89(cls):
        return cls(89)
    
    @schemas.classproperty
    def POSITIVE_90(cls):
        return cls(90)
    
    @schemas.classproperty
    def POSITIVE_91(cls):
        return cls(91)
    
    @schemas.classproperty
    def POSITIVE_92(cls):
        return cls(92)
    
    @schemas.classproperty
    def POSITIVE_93(cls):
        return cls(93)
    
    @schemas.classproperty
    def POSITIVE_94(cls):
        return cls(94)
    
    @schemas.classproperty
    def POSITIVE_95(cls):
        return cls(95)
    
    @schemas.classproperty
    def POSITIVE_96(cls):
        return cls(96)
    
    @schemas.classproperty
    def POSITIVE_97(cls):
        return cls(97)
    
    @schemas.classproperty
    def POSITIVE_98(cls):
        return cls(98)
    
    @schemas.classproperty
    def POSITIVE_99(cls):
        return cls(99)
    
    @schemas.classproperty
    def POSITIVE_100(cls):
        return cls(100)
    
    @schemas.classproperty
    def POSITIVE_101(cls):
        return cls(101)
    
    @schemas.classproperty
    def POSITIVE_102(cls):
        return cls(102)
    
    @schemas.classproperty
    def POSITIVE_103(cls):
        return cls(103)
    
    @schemas.classproperty
    def POSITIVE_104(cls):
        return cls(104)
    
    @schemas.classproperty
    def POSITIVE_105(cls):
        return cls(105)
    
    @schemas.classproperty
    def POSITIVE_106(cls):
        return cls(106)
    
    @schemas.classproperty
    def POSITIVE_107(cls):
        return cls(107)
    
    @schemas.classproperty
    def POSITIVE_108(cls):
        return cls(108)
    
    @schemas.classproperty
    def POSITIVE_109(cls):
        return cls(109)
