# coding: utf-8

"""
    Shoko API 3

    Shoko Server API.  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from lib.shoko.v3 import schemas  # noqa: F401


class DebugControllerAnidbUdpResponse(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    A response from the AniDB UDP API.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def Code() -> typing.Type['AniDBUDPReturnCode']:
                return AniDBUDPReturnCode
            
            
            class Response(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'Response':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "Code": Code,
                "Response": Response,
            }
        additional_properties = schemas.NotAnyTypeSchema
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Code"]) -> 'AniDBUDPReturnCode': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Response"]) -> MetaOapg.properties.Response: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["Code"], typing_extensions.Literal["Response"], ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Code"]) -> typing.Union['AniDBUDPReturnCode', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Response"]) -> typing.Union[MetaOapg.properties.Response, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["Code"], typing_extensions.Literal["Response"], ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        Code: typing.Union['AniDBUDPReturnCode', schemas.Unset] = schemas.unset,
        Response: typing.Union[MetaOapg.properties.Response, None, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'DebugControllerAnidbUdpResponse':
        return super().__new__(
            cls,
            *_args,
            Code=Code,
            Response=Response,
            _configuration=_configuration,
        )

from lib.shoko.v3.lib.shoko.v3.models.ani_dbudp_return_code import AniDBUDPReturnCode
