# coding: utf-8

"""
    Shoko API 3

    Shoko Server API.  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from lib.shoko.v3 import schemas  # noqa: F401


class FileLocation(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "IsAccessible",
        }
        
        class properties:
            IsAccessible = schemas.BoolSchema
            ImportFolderID = schemas.Int32Schema
            
            
            class RelativePath(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'RelativePath':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "IsAccessible": IsAccessible,
                "ImportFolderID": ImportFolderID,
                "RelativePath": RelativePath,
            }
        additional_properties = schemas.NotAnyTypeSchema
    
    IsAccessible: MetaOapg.properties.IsAccessible
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["IsAccessible"]) -> MetaOapg.properties.IsAccessible: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ImportFolderID"]) -> MetaOapg.properties.ImportFolderID: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["RelativePath"]) -> MetaOapg.properties.RelativePath: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["IsAccessible"], typing_extensions.Literal["ImportFolderID"], typing_extensions.Literal["RelativePath"], ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["IsAccessible"]) -> MetaOapg.properties.IsAccessible: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ImportFolderID"]) -> typing.Union[MetaOapg.properties.ImportFolderID, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["RelativePath"]) -> typing.Union[MetaOapg.properties.RelativePath, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["IsAccessible"], typing_extensions.Literal["ImportFolderID"], typing_extensions.Literal["RelativePath"], ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        IsAccessible: typing.Union[MetaOapg.properties.IsAccessible, bool, ],
        ImportFolderID: typing.Union[MetaOapg.properties.ImportFolderID, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        RelativePath: typing.Union[MetaOapg.properties.RelativePath, None, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'FileLocation':
        return super().__new__(
            cls,
            *_args,
            IsAccessible=IsAccessible,
            ImportFolderID=ImportFolderID,
            RelativePath=RelativePath,
            _configuration=_configuration,
        )
