# coding: utf-8

"""
    Shoko API 3

    Shoko Server API.  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from lib.shoko.v3 import schemas  # noqa: F401


class ImageImageType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Image type.
    """
    
    @schemas.classproperty
    def POSTER(cls):
        return cls("Poster")
    
    @schemas.classproperty
    def BANNER(cls):
        return cls("Banner")
    
    @schemas.classproperty
    def THUMB(cls):
        return cls("Thumb")
    
    @schemas.classproperty
    def FANART(cls):
        return cls("Fanart")
    
    @schemas.classproperty
    def CHARACTER(cls):
        return cls("Character")
    
    @schemas.classproperty
    def STAFF(cls):
        return cls("Staff")
    
    @schemas.classproperty
    def AVATAR(cls):
        return cls("Avatar")
    
    @schemas.classproperty
    def STATIC(cls):
        return cls("Static")
