# coding: utf-8

"""
    Shoko API 3

    Shoko Server API.  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from lib.shoko.v3 import schemas  # noqa: F401


class ImageImageSource(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Image source.
    """
    
    @schemas.classproperty
    def ANI_DB(cls):
        return cls("AniDB")
    
    @schemas.classproperty
    def TV_DB(cls):
        return cls("TvDB")
    
    @schemas.classproperty
    def TMDB(cls):
        return cls("TMDB")
    
    @schemas.classproperty
    def USER(cls):
        return cls("User")
    
    @schemas.classproperty
    def SHOKO(cls):
        return cls("Shoko")
