# coding: utf-8

"""
    Shoko API 3

    Shoko Server API.  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from lib.shoko.v3 import schemas  # noqa: F401


class InputLinkSeriesBody(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Link a file to an episode range in a series.
    """


    class MetaOapg:
        required = {
            "RangeEnd",
            "SeriesID",
            "RangeStart",
        }
        
        class properties:
            SeriesID = schemas.Int32Schema
            
            
            class RangeStart(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    min_length = 1
            
            
            class RangeEnd(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    min_length = 1
            __annotations__ = {
                "SeriesID": SeriesID,
                "RangeStart": RangeStart,
                "RangeEnd": RangeEnd,
            }
        additional_properties = schemas.NotAnyTypeSchema
    
    RangeEnd: MetaOapg.properties.RangeEnd
    SeriesID: MetaOapg.properties.SeriesID
    RangeStart: MetaOapg.properties.RangeStart
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["RangeEnd"]) -> MetaOapg.properties.RangeEnd: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["SeriesID"]) -> MetaOapg.properties.SeriesID: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["RangeStart"]) -> MetaOapg.properties.RangeStart: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["RangeEnd"], typing_extensions.Literal["SeriesID"], typing_extensions.Literal["RangeStart"], ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["RangeEnd"]) -> MetaOapg.properties.RangeEnd: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["SeriesID"]) -> MetaOapg.properties.SeriesID: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["RangeStart"]) -> MetaOapg.properties.RangeStart: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["RangeEnd"], typing_extensions.Literal["SeriesID"], typing_extensions.Literal["RangeStart"], ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        RangeEnd: typing.Union[MetaOapg.properties.RangeEnd, str, ],
        SeriesID: typing.Union[MetaOapg.properties.SeriesID, decimal.Decimal, int, ],
        RangeStart: typing.Union[MetaOapg.properties.RangeStart, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'InputLinkSeriesBody':
        return super().__new__(
            cls,
            *_args,
            RangeEnd=RangeEnd,
            SeriesID=SeriesID,
            RangeStart=RangeStart,
            _configuration=_configuration,
        )
