# coding: utf-8

"""
    Shoko API 3

    Shoko Server API.  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from lib.shoko.v3 import schemas  # noqa: F401


class SeriesSizesFileSourceCounts(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            Unknown = schemas.Int32Schema
            Other = schemas.Int32Schema
            TV = schemas.Int32Schema
            DVD = schemas.Int32Schema
            BluRay = schemas.Int32Schema
            Web = schemas.Int32Schema
            VHS = schemas.Int32Schema
            VCD = schemas.Int32Schema
            LaserDisc = schemas.Int32Schema
            Camera = schemas.Int32Schema
            __annotations__ = {
                "Unknown": Unknown,
                "Other": Other,
                "TV": TV,
                "DVD": DVD,
                "BluRay": BluRay,
                "Web": Web,
                "VHS": VHS,
                "VCD": VCD,
                "LaserDisc": LaserDisc,
                "Camera": Camera,
            }
        additional_properties = schemas.NotAnyTypeSchema
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Unknown"]) -> MetaOapg.properties.Unknown: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Other"]) -> MetaOapg.properties.Other: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["TV"]) -> MetaOapg.properties.TV: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["DVD"]) -> MetaOapg.properties.DVD: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["BluRay"]) -> MetaOapg.properties.BluRay: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Web"]) -> MetaOapg.properties.Web: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["VHS"]) -> MetaOapg.properties.VHS: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["VCD"]) -> MetaOapg.properties.VCD: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["LaserDisc"]) -> MetaOapg.properties.LaserDisc: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Camera"]) -> MetaOapg.properties.Camera: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["Unknown"], typing_extensions.Literal["Other"], typing_extensions.Literal["TV"], typing_extensions.Literal["DVD"], typing_extensions.Literal["BluRay"], typing_extensions.Literal["Web"], typing_extensions.Literal["VHS"], typing_extensions.Literal["VCD"], typing_extensions.Literal["LaserDisc"], typing_extensions.Literal["Camera"], ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Unknown"]) -> typing.Union[MetaOapg.properties.Unknown, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Other"]) -> typing.Union[MetaOapg.properties.Other, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["TV"]) -> typing.Union[MetaOapg.properties.TV, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["DVD"]) -> typing.Union[MetaOapg.properties.DVD, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["BluRay"]) -> typing.Union[MetaOapg.properties.BluRay, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Web"]) -> typing.Union[MetaOapg.properties.Web, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["VHS"]) -> typing.Union[MetaOapg.properties.VHS, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["VCD"]) -> typing.Union[MetaOapg.properties.VCD, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["LaserDisc"]) -> typing.Union[MetaOapg.properties.LaserDisc, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Camera"]) -> typing.Union[MetaOapg.properties.Camera, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["Unknown"], typing_extensions.Literal["Other"], typing_extensions.Literal["TV"], typing_extensions.Literal["DVD"], typing_extensions.Literal["BluRay"], typing_extensions.Literal["Web"], typing_extensions.Literal["VHS"], typing_extensions.Literal["VCD"], typing_extensions.Literal["LaserDisc"], typing_extensions.Literal["Camera"], ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        Unknown: typing.Union[MetaOapg.properties.Unknown, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        Other: typing.Union[MetaOapg.properties.Other, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        TV: typing.Union[MetaOapg.properties.TV, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        DVD: typing.Union[MetaOapg.properties.DVD, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        BluRay: typing.Union[MetaOapg.properties.BluRay, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        Web: typing.Union[MetaOapg.properties.Web, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        VHS: typing.Union[MetaOapg.properties.VHS, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        VCD: typing.Union[MetaOapg.properties.VCD, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        LaserDisc: typing.Union[MetaOapg.properties.LaserDisc, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        Camera: typing.Union[MetaOapg.properties.Camera, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'SeriesSizesFileSourceCounts':
        return super().__new__(
            cls,
            *_args,
            Unknown=Unknown,
            Other=Other,
            TV=TV,
            DVD=DVD,
            BluRay=BluRay,
            Web=Web,
            VHS=VHS,
            VCD=VCD,
            LaserDisc=LaserDisc,
            Camera=Camera,
            _configuration=_configuration,
        )
