# coding: utf-8

"""
    Shoko API 3

    Shoko Server API.  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from lib.shoko.v3 import schemas  # noqa: F401


class ShokoChildItems(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            Folders = schemas.Int32Schema
            Files = schemas.Int32Schema
            __annotations__ = {
                "Folders": Folders,
                "Files": Files,
            }
        additional_properties = schemas.NotAnyTypeSchema
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Folders"]) -> MetaOapg.properties.Folders: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["Files"]) -> MetaOapg.properties.Files: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["Folders"], typing_extensions.Literal["Files"], ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Folders"]) -> typing.Union[MetaOapg.properties.Folders, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["Files"]) -> typing.Union[MetaOapg.properties.Files, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["Folders"], typing_extensions.Literal["Files"], ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        Folders: typing.Union[MetaOapg.properties.Folders, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        Files: typing.Union[MetaOapg.properties.Files, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'ShokoChildItems':
        return super().__new__(
            cls,
            *_args,
            Folders=Folders,
            Files=Files,
            _configuration=_configuration,
        )
