# coding: utf-8

"""
    Shoko API 3

    Shoko Server API.  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

import unittest

import lib.shoko.v3
from lib.shoko.v3.lib.shoko.v3.models.series_resource import SeriesResource
from lib.shoko.v3 import configuration


class TestSeriesResource(unittest.TestCase):
    """SeriesResource unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
