# coding: utf-8

"""
    Shoko API 3

    Shoko Server API.  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

import unittest

import lib.shoko.v3
from lib.shoko.v3.lib.shoko.v3.models.ani_db_ani_db_release_group import AniDBAniDBReleaseGroup
from lib.shoko.v3 import configuration


class TestAniDBAniDBReleaseGroup(unittest.TestCase):
    """AniDBAniDBReleaseGroup unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
