# coding: utf-8

# flake8: noqa

"""
    Shoko API 3

    Shoko Server API.  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from lib.shoko.v3.api_client import ApiClient

# import Configuration
from lib.shoko.v3.configuration import Configuration

# import exceptions
from lib.shoko.v3.exceptions import OpenApiException
from lib.shoko.v3.exceptions import ApiAttributeError
from lib.shoko.v3.exceptions import ApiTypeError
from lib.shoko.v3.exceptions import ApiValueError
from lib.shoko.v3.exceptions import ApiKeyError
from lib.shoko.v3.exceptions import ApiException
