# coding: utf-8

"""
    Shoko API 3

    Shoko Server API.  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

from lib.shoko.v3.paths.dashboard_ani_db_calendar.get import DashboardAniDbCalendarGet
from lib.shoko.v3.paths.dashboard_continue_watching_episodes.get import DashboardContinueWatchingEpisodesGet
from lib.shoko.v3.paths.dashboard_next_up_episodes.get import DashboardNextUpEpisodesGet
from lib.shoko.v3.paths.dashboard_queue_summary.get import DashboardQueueSummaryGet
from lib.shoko.v3.paths.dashboard_recently_added_episodes.get import DashboardRecentlyAddedEpisodesGet
from lib.shoko.v3.paths.dashboard_recently_added_series.get import DashboardRecentlyAddedSeriesGet
from lib.shoko.v3.paths.dashboard_series_summary.get import DashboardSeriesSummaryGet
from lib.shoko.v3.paths.dashboard_stats.get import DashboardStatsGet
from lib.shoko.v3.paths.dashboard_top_tags.get import DashboardTopTagsGet
from lib.shoko.v3.paths.dashboard_top_tags_number.get import DashboardTopTagsNumberGet


class DashboardApi(
    DashboardAniDbCalendarGet,
    DashboardContinueWatchingEpisodesGet,
    DashboardNextUpEpisodesGet,
    DashboardQueueSummaryGet,
    DashboardRecentlyAddedEpisodesGet,
    DashboardRecentlyAddedSeriesGet,
    DashboardSeriesSummaryGet,
    DashboardStatsGet,
    DashboardTopTagsGet,
    DashboardTopTagsNumberGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
