# coding: utf-8

"""
    Shoko API 3

    Shoko Server API.  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

from lib.shoko.v3.paths.episode_ani_db_anidb_episode_id_episode.get import EpisodeAniDbAnidbEpisodeIdEpisodeGet
from lib.shoko.v3.paths.episode_ani_db_anidb_episode_id.get import EpisodeAniDbAnidbEpisodeIdGet
from lib.shoko.v3.paths.episode_ani_db.get import EpisodeAniDbGet
from lib.shoko.v3.paths.episode_episode_id_ani_db.get import EpisodeEpisodeIdAniDbGet
from lib.shoko.v3.paths.episode_episode_id.get import EpisodeEpisodeIdGet
from lib.shoko.v3.paths.episode_episode_id_set_hidden.post import EpisodeEpisodeIdSetHiddenPost
from lib.shoko.v3.paths.episode_episode_id_vote.post import EpisodeEpisodeIdVotePost
from lib.shoko.v3.paths.episode_episode_id_watched_watched.post import EpisodeEpisodeIdWatchedWatchedPost
from lib.shoko.v3.paths.episode_episode_id_tv_db.get import EpisodeEpisodeIdtvDbGet
from lib.shoko.v3.paths.episode.get import EpisodeGet
from lib.shoko.v3.paths.episode_tv_db.get import EpisodeTvDbGet
from lib.shoko.v3.paths.episode_with_multiple_files.get import EpisodeWithMultipleFilesGet
from lib.shoko.v3.paths.episode_with_no_files.get import EpisodeWithNoFilesGet


class EpisodeApi(
    EpisodeAniDbAnidbEpisodeIdEpisodeGet,
    EpisodeAniDbAnidbEpisodeIdGet,
    EpisodeAniDbGet,
    EpisodeEpisodeIdAniDbGet,
    EpisodeEpisodeIdGet,
    EpisodeEpisodeIdSetHiddenPost,
    EpisodeEpisodeIdVotePost,
    EpisodeEpisodeIdWatchedWatchedPost,
    EpisodeEpisodeIdtvDbGet,
    EpisodeGet,
    EpisodeTvDbGet,
    EpisodeWithMultipleFilesGet,
    EpisodeWithNoFilesGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
