# coding: utf-8

"""
    Shoko API 3

    Shoko Server API.  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

from lib.shoko.v3.paths.filter_filter_id.delete import FilterFilterIdDelete
from lib.shoko.v3.paths.filter_filter_id.get import FilterFilterIdGet
from lib.shoko.v3.paths.filter_filter_id.patch import FilterFilterIdPatch
from lib.shoko.v3.paths.filter_filter_id.put import FilterFilterIdPut
from lib.shoko.v3.paths.filter.get import FilterGet
from lib.shoko.v3.paths.filter.post import FilterPost
from lib.shoko.v3.paths.filter_preview.delete import FilterPreviewDelete
from lib.shoko.v3.paths.filter_preview.get import FilterPreviewGet
from lib.shoko.v3.paths.filter_preview_group.get import FilterPreviewGroupGet
from lib.shoko.v3.paths.filter_preview_group_group_id_group.get import FilterPreviewGroupGroupIdGroupGet
from lib.shoko.v3.paths.filter_preview_group_group_id_series.get import FilterPreviewGroupGroupIdSeriesGet
from lib.shoko.v3.paths.filter_preview_group_letters.get import FilterPreviewGroupLettersGet
from lib.shoko.v3.paths.filter_preview.patch import FilterPreviewPatch
from lib.shoko.v3.paths.filter_preview.put import FilterPreviewPut
from lib.shoko.v3.paths.filter_preview_series.get import FilterPreviewSeriesGet


class FilterApi(
    FilterFilterIdDelete,
    FilterFilterIdGet,
    FilterFilterIdPatch,
    FilterFilterIdPut,
    FilterGet,
    FilterPost,
    FilterPreviewDelete,
    FilterPreviewGet,
    FilterPreviewGroupGet,
    FilterPreviewGroupGroupIdGroupGet,
    FilterPreviewGroupGroupIdSeriesGet,
    FilterPreviewGroupLettersGet,
    FilterPreviewPatch,
    FilterPreviewPut,
    FilterPreviewSeriesGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
