# coding: utf-8

"""
    Shoko API 3

    Shoko Server API.  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

from lib.shoko.v3.paths.import_folder_folder_id.delete import ImportFolderFolderIdDelete
from lib.shoko.v3.paths.import_folder_folder_id.get import ImportFolderFolderIdGet
from lib.shoko.v3.paths.import_folder_folder_id.patch import ImportFolderFolderIdPatch
from lib.shoko.v3.paths.import_folder_folder_id_scan.get import ImportFolderFolderIdScanGet
from lib.shoko.v3.paths.import_folder.get import ImportFolderGet
from lib.shoko.v3.paths.import_folder.post import ImportFolderPost
from lib.shoko.v3.paths.import_folder.put import ImportFolderPut


class ImportFolderApi(
    ImportFolderFolderIdDelete,
    ImportFolderFolderIdGet,
    ImportFolderFolderIdPatch,
    ImportFolderFolderIdScanGet,
    ImportFolderGet,
    ImportFolderPost,
    ImportFolderPut,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
