# coding: utf-8

"""
    Shoko API 3

    Shoko Server API.  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

from lib.shoko.v3.paths.renamer.get import RenamerGet
from lib.shoko.v3.paths.renamer_renamer_id.delete import RenamerRenamerIdDelete
from lib.shoko.v3.paths.renamer_renamer_id.patch import RenamerRenamerIdPatch


class RenamerApi(
    RenamerGet,
    RenamerRenamerIdDelete,
    RenamerRenamerIdPatch,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
