# coding: utf-8

"""
    Shoko API 3

    Shoko Server API.  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

from lib.shoko.v3.paths.episode_episode_id_series.get import EpisodeEpisodeIdSeriesGet
from lib.shoko.v3.paths.file_file_id_episode.get import FileFileIdEpisodeGet
from lib.shoko.v3.paths.filter_filter_id_parent.get import FilterFilterIdParentGet
from lib.shoko.v3.paths.group_group_id_parent.get import GroupGroupIdParentGet
from lib.shoko.v3.paths.series_series_id_group.get import SeriesSeriesIdGroupGet


class ReverseTreeApi(
    EpisodeEpisodeIdSeriesGet,
    FileFileIdEpisodeGet,
    FilterFilterIdParentGet,
    GroupGroupIdParentGet,
    SeriesSeriesIdGroupGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
