# coding: utf-8

"""
    Shoko API 3

    Shoko Server API.  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

from lib.shoko.v3.paths.series_ani_db_anidb_id.get import SeriesAniDbAnidbIdGet
from lib.shoko.v3.paths.series_ani_db_anidb_id_refresh.post import SeriesAniDbAnidbIdRefreshPost
from lib.shoko.v3.paths.series_ani_db_anidb_id_related.get import SeriesAniDbAnidbIdRelatedGet
from lib.shoko.v3.paths.series_ani_db_anidb_id_relations.get import SeriesAniDbAnidbIdRelationsGet
from lib.shoko.v3.paths.series_ani_db_anidb_id_series.get import SeriesAniDbAnidbIdSeriesGet
from lib.shoko.v3.paths.series_ani_db_anidb_id_similar.get import SeriesAniDbAnidbIdSimilarGet
from lib.shoko.v3.paths.series_ani_db.get import SeriesAniDbGet
from lib.shoko.v3.paths.series_ani_db_recommended_for_you.get import SeriesAniDbRecommendedForYouGet
from lib.shoko.v3.paths.series_ani_db_relations.get import SeriesAniDbRelationsGet
from lib.shoko.v3.paths.series_ani_db_search.get import SeriesAniDbSearchGet
from lib.shoko.v3.paths.series_ani_db_search_query.get import SeriesAniDbSearchQueryGet
from lib.shoko.v3.paths.series.get import SeriesGet
from lib.shoko.v3.paths.series_path_ends_with_path.get import SeriesPathEndsWithPathGet
from lib.shoko.v3.paths.series_search.get import SeriesSearchGet
from lib.shoko.v3.paths.series_search_query.get import SeriesSearchQueryGet
from lib.shoko.v3.paths.series_series_id_ani_db.get import SeriesSeriesIdAniDbGet
from lib.shoko.v3.paths.series_series_id_ani_db_refresh_force_from_xml.post import SeriesSeriesIdAniDbRefreshForceFromXmlPost
from lib.shoko.v3.paths.series_series_id_ani_db_refresh.post import SeriesSeriesIdAniDbRefreshPost
from lib.shoko.v3.paths.series_series_id_ani_db_related.get import SeriesSeriesIdAniDbRelatedGet
from lib.shoko.v3.paths.series_series_id_ani_db_relations.get import SeriesSeriesIdAniDbRelationsGet
from lib.shoko.v3.paths.series_series_id_ani_db_similar.get import SeriesSeriesIdAniDbSimilarGet
from lib.shoko.v3.paths.series_series_id_auto_match_settings.get import SeriesSeriesIdAutoMatchSettingsGet
from lib.shoko.v3.paths.series_series_id_auto_match_settings.patch import SeriesSeriesIdAutoMatchSettingsPatch
from lib.shoko.v3.paths.series_series_id_auto_match_settings.put import SeriesSeriesIdAutoMatchSettingsPut
from lib.shoko.v3.paths.series_series_id_cast.get import SeriesSeriesIdCastGet
from lib.shoko.v3.paths.series_series_id.delete import SeriesSeriesIdDelete
from lib.shoko.v3.paths.series_series_id.get import SeriesSeriesIdGet
from lib.shoko.v3.paths.series_series_id_images.get import SeriesSeriesIdImagesGet
from lib.shoko.v3.paths.series_series_id_images_image_type.delete import SeriesSeriesIdImagesImageTypeDelete
from lib.shoko.v3.paths.series_series_id_images_image_type.get import SeriesSeriesIdImagesImageTypeGet
from lib.shoko.v3.paths.series_series_id_images_image_type.put import SeriesSeriesIdImagesImageTypePut
from lib.shoko.v3.paths.series_series_id_move_group_id.patch import SeriesSeriesIdMoveGroupIdPatch
from lib.shoko.v3.paths.series_series_id_relations.get import SeriesSeriesIdRelationsGet
from lib.shoko.v3.paths.series_series_id_tags_filter.get import SeriesSeriesIdTagsFilterGet
from lib.shoko.v3.paths.series_series_id_tags.get import SeriesSeriesIdTagsGet
from lib.shoko.v3.paths.series_series_id_tvdb_id_refresh.post import SeriesSeriesIdTvdbIdRefreshPost
from lib.shoko.v3.paths.series_series_id_vote.post import SeriesSeriesIdVotePost
from lib.shoko.v3.paths.series_series_id_tv_db.get import SeriesSeriesIdtvDbGet
from lib.shoko.v3.paths.series_starts_with_query.get import SeriesStartsWithQueryGet
from lib.shoko.v3.paths.series_tv_db_tvdb_id.get import SeriesTvDbTvdbIdGet
from lib.shoko.v3.paths.series_tv_db_tvdb_id_refresh.post import SeriesTvDbTvdbIdRefreshPost
from lib.shoko.v3.paths.series_tv_db_tvdb_id_series.get import SeriesTvDbTvdbIdSeriesGet
from lib.shoko.v3.paths.series_with_manually_linked_files.get import SeriesWithManuallyLinkedFilesGet
from lib.shoko.v3.paths.series_without_files.get import SeriesWithoutFilesGet


class SeriesApi(
    SeriesAniDbAnidbIdGet,
    SeriesAniDbAnidbIdRefreshPost,
    SeriesAniDbAnidbIdRelatedGet,
    SeriesAniDbAnidbIdRelationsGet,
    SeriesAniDbAnidbIdSeriesGet,
    SeriesAniDbAnidbIdSimilarGet,
    SeriesAniDbGet,
    SeriesAniDbRecommendedForYouGet,
    SeriesAniDbRelationsGet,
    SeriesAniDbSearchGet,
    SeriesAniDbSearchQueryGet,
    SeriesGet,
    SeriesPathEndsWithPathGet,
    SeriesSearchGet,
    SeriesSearchQueryGet,
    SeriesSeriesIdAniDbGet,
    SeriesSeriesIdAniDbRefreshForceFromXmlPost,
    SeriesSeriesIdAniDbRefreshPost,
    SeriesSeriesIdAniDbRelatedGet,
    SeriesSeriesIdAniDbRelationsGet,
    SeriesSeriesIdAniDbSimilarGet,
    SeriesSeriesIdAutoMatchSettingsGet,
    SeriesSeriesIdAutoMatchSettingsPatch,
    SeriesSeriesIdAutoMatchSettingsPut,
    SeriesSeriesIdCastGet,
    SeriesSeriesIdDelete,
    SeriesSeriesIdGet,
    SeriesSeriesIdImagesGet,
    SeriesSeriesIdImagesImageTypeDelete,
    SeriesSeriesIdImagesImageTypeGet,
    SeriesSeriesIdImagesImageTypePut,
    SeriesSeriesIdMoveGroupIdPatch,
    SeriesSeriesIdRelationsGet,
    SeriesSeriesIdTagsFilterGet,
    SeriesSeriesIdTagsGet,
    SeriesSeriesIdTvdbIdRefreshPost,
    SeriesSeriesIdVotePost,
    SeriesSeriesIdtvDbGet,
    SeriesStartsWithQueryGet,
    SeriesTvDbTvdbIdGet,
    SeriesTvDbTvdbIdRefreshPost,
    SeriesTvDbTvdbIdSeriesGet,
    SeriesWithManuallyLinkedFilesGet,
    SeriesWithoutFilesGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
