# coding: utf-8

"""
    Shoko API 3

    Shoko Server API.  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

from lib.shoko.v3.paths.episode_episode_id_file.get import EpisodeEpisodeIdFileGet
from lib.shoko.v3.paths.filter_filter_id_filter.get import FilterFilterIdFilterGet
from lib.shoko.v3.paths.filter_filter_id_group.get import FilterFilterIdGroupGet
from lib.shoko.v3.paths.filter_filter_id_group_group_id_group.get import FilterFilterIdGroupGroupIdGroupGet
from lib.shoko.v3.paths.filter_filter_id_group_group_id_series.get import FilterFilterIdGroupGroupIdSeriesGet
from lib.shoko.v3.paths.filter_filter_id_group_letters.get import FilterFilterIdGroupLettersGet
from lib.shoko.v3.paths.filter_filter_id_series.get import FilterFilterIdSeriesGet
from lib.shoko.v3.paths.group_group_id_group.get import GroupGroupIdGroupGet
from lib.shoko.v3.paths.group_group_id_main_series.get import GroupGroupIdMainSeriesGet
from lib.shoko.v3.paths.group_group_id_series.get import GroupGroupIdSeriesGet
from lib.shoko.v3.paths.import_folder_folder_id_file.get import ImportFolderFolderIdFileGet
from lib.shoko.v3.paths.series_series_id_episode.get import SeriesSeriesIdEpisodeGet
from lib.shoko.v3.paths.series_series_id_file.get import SeriesSeriesIdFileGet
from lib.shoko.v3.paths.series_series_id_next_up_episode.get import SeriesSeriesIdNextUpEpisodeGet


class TreeApi(
    EpisodeEpisodeIdFileGet,
    FilterFilterIdFilterGet,
    FilterFilterIdGroupGet,
    FilterFilterIdGroupGroupIdGroupGet,
    FilterFilterIdGroupGroupIdSeriesGet,
    FilterFilterIdGroupLettersGet,
    FilterFilterIdSeriesGet,
    GroupGroupIdGroupGet,
    GroupGroupIdMainSeriesGet,
    GroupGroupIdSeriesGet,
    ImportFolderFolderIdFileGet,
    SeriesSeriesIdEpisodeGet,
    SeriesSeriesIdFileGet,
    SeriesSeriesIdNextUpEpisodeGet,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
