# coding: utf-8

"""
    Shoko API 3

    Shoko Server API.  # noqa: E501

    The version of the OpenAPI document: 3
    Generated by: https://openapi-generator.tech
"""

from lib.shoko.v3.paths.user_current_change_password.post import UserCurrentChangePasswordPost
from lib.shoko.v3.paths.user_current.get import UserCurrentGet
from lib.shoko.v3.paths.user_current.patch import UserCurrentPatch
from lib.shoko.v3.paths.user_current.put import UserCurrentPut
from lib.shoko.v3.paths.user.get import UserGet
from lib.shoko.v3.paths.user.post import UserPost
from lib.shoko.v3.paths.user_user_id_change_password.post import UserUserIdChangePasswordPost
from lib.shoko.v3.paths.user_user_id.delete import UserUserIdDelete
from lib.shoko.v3.paths.user_user_id.get import UserUserIdGet
from lib.shoko.v3.paths.user_user_id.patch import UserUserIdPatch
from lib.shoko.v3.paths.user_user_id.put import UserUserIdPut


class UserApi(
    UserCurrentChangePasswordPost,
    UserCurrentGet,
    UserCurrentPatch,
    UserCurrentPut,
    UserGet,
    UserPost,
    UserUserIdChangePasswordPost,
    UserUserIdDelete,
    UserUserIdGet,
    UserUserIdPatch,
    UserUserIdPut,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
